#!/bin/bash
# Gather a locked environment.
conda env export > ./environment.lock.yml

# Remove quantco_main channel from the environment.lock.yml
sed -i '/quantco_main/d' ./environment.lock.yml
cp -R _build/html/* ../../tbenthompson_site/static/book/

echo "Please git commit!"
