#!/bin/bash

# Open the refresh script and modify it for your browser/platform...

trap "kill 0" EXIT

python -m http.server -d _build/html &> /dev/null &

while true
do
{ git ls-files; git ls-files . --exclude-standard --others; } | entr -d ./update
done

wait
