#!/bin/bash -i
target_repo=~/Dropbox/active/tbenthompson_site
target_dir=static/book

conda activate tectosaur2
jupyter book build .

# Gather a locked environment.
conda env export > ./environment.lock.yml

pushd $target_repo
if [ -z "$(git status --porcelain)" ]; then
    # Delete existing files.
    git rm -r $target_dir
    popd

    # Copy new files
    cp -R _build/html/* $target_repo/$target_dir

    # Add new files and then commit and push.
    pushd $target_repo
    git add $target_dir
    git commit -m "Publish BIE book."
    git push origin master
    popd
else
    echo "$target_repo has unclean git status. Please git stash or commit before re-running publish."
    exit;
fi

git status

echo "Please run git commit here."
